@startuml

actor Veterinario

boundary TelaVacinacao
control VacinaController
control VacinaService
entity Animal
entity Vacina
database BancoDeDados

Veterinario -> TelaVacinacao : informarVacina()
activate TelaVacinacao

TelaVacinacao -> VacinaController : registrarVacina()
activate VacinaController

VacinaController -> VacinaService : validarAplicacao()
activate VacinaService

VacinaService -> Animal : verificarCadastro()
activate Animal

Animal --> VacinaService : animalValido
deactivate Animal

alt Animal cadastrado

    VacinaService -> Vacina : criarRegistro()
    activate Vacina

    Vacina --> VacinaService : registroCriado
    deactivate Vacina

    VacinaService -> BancoDeDados : salvarRegistro()
    activate BancoDeDados

    BancoDeDados --> VacinaService : sucesso
    deactivate BancoDeDados

    VacinaService --> VacinaController : confirmação

else Animal não encontrado

    VacinaService --> VacinaController : erro

end

deactivate VacinaService

VacinaController --> TelaVacinacao : exibirResultado()
deactivate VacinaController

TelaVacinacao --> Veterinario : confirmação
deactivate TelaVacinacao

@enduml
